baseURL = "https://crossphoton.tech"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Aditya Agrawal"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "I'm Aditya Agrawal"
author = "crossphoton"
#copyright = "2020-2021"
description = "Call me ADI"
profilePicture = "/images/pic.jpg"
keywords = ""
displayMode = "light"
fullPostContent = true
gtagId = "G-XPQF8X0C5Z"



## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/crossphoton"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/crossphoton/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/crossphoton"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:aditya@crossphoton.tech"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/grownupadi"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 300
  identifier = "contact"
  url = "/contact/"