title = "Aditya Agrawal"
baseURL = "https://crossphoton.tech"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
lastName = "Agrawal"
showOpenSource = false
showPublications = false
showExperience = false
showEducation = true
phone = "9785559273"
profileImage = "img/pic.webp"
favicon = "https://crossphoton.tech/pic.webp"
address = "Jaipur, RJ"
showProjects = false
firstName = "Aditya"
email = "adiag1200+website@gmail.com"
showQr = true
showSkills = true

[[params.handles]]
link = "https://www.linkedin.com/in/crossphoton/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/crossphoton/"
name = "GitHub"

[[params.handles]]
link = "https://twitter.com/crossphoton/"
name = "Twitter"

[[params.handles]]
link = "https://crossphoton.medium.com"
name = "Medium"

[[params.handles]]
link = "https://crossphoton.tech/cdn/CV.pdf"
name = "Resume"
icon = "creative-commons-share"

[params.google]

[params.google.analytics]
trackerID = "G-XPQF8X0C5Z"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"