title = "Aditya Agrawal"
baseURL = "https://crossphoton.tech"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Jaipur, RJ"
email = "adiag1200+website@gmail.com"
favicon = "https://crossphoton.tech/pic.webp"
firstName = "Aditya"
lastName = "Agrawal"
profileImage = "img/pic.webp"
showEducation = true
showQr = true
showSkills = true
showExperience = false
showOpenSource = false
showProjects = false
showPublications = false

[params.google]

[params.google.analytics]
trackerID = "G-XPQF8X0C5Z"

[[params.handles]]
link = "https://www.linkedin.com/in/crossphoton/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/crossphoton/"
name = "GitHub"

[[params.handles]]
link = "https://twitter.com/crossphoton/"
name = "Twitter"

[[params.handles]]
link = "https://crossphoton.medium.com"
name = "Medium"

[[params.handles]]
link = "https://crossphoton.tech/cnd/CV.pdf"
name = "Resume"
icon = "creative-commons-share"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"